kind: pipeline
name: Kaze風

clone:
        depth: 1

steps:
  - name: compile
    image: thagoo/triton-proton:latest
    environment:
            TOKEN:
                    from_secret: token
            CID:
                    from_secret: cid
    commands:
      - wget https://raw.githubusercontent.com/anggialansori404/triton-scripts/kaze/compiler.sh
      - chmod +x compiler.sh
      - bash compiler.sh